# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone("https://github.com/femtotrader/TimeFrames.jl")'
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("TimeSeriesResampler"); Pkg.test("TimeSeriesResampler"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("TimeSeriesResampler")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TimeSeriesResampler")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
